### ISSUE TITLE
Multi-line Support

### ISSUE THREAD

**Issue by Scamper10** [oOBoomberOo/tellraw-preview#9]
The extension does not currently support multi-line commands (created with `\`).

Example:
```
tellraw @a "this is a \
valid mcfunction."
```

Chat output:
`this is a valid mcfunction.`

Preview output:
_`Δ Unterminated string in JSON at position 13 (Line 1 column 14)`_

**Comment by oOBoomberOo** [comment]
This should work now.

![image](https://github.com/user-attachments/assets/ea298185-e577-47cf-9c96-2bc0222c871c)

**Comment by Scamper10** [comment]
Thanks for implementing my thing :)
However..

Doing this inside a string still causes problems:
![image](https://github.com/user-attachments/assets/30f06033-102a-427a-ac6f-7e921e682dfc)

This too:
![image](https://github.com/user-attachments/assets/b2a4a288-51b9-4beb-bb27-d2a61239e486)

Now I've started I can't stop
Is this the extension too? There aren't any chat commands here...
![image](https://github.com/user-attachments/assets/c19de757-a9a6-44b6-87b7-979316e279c6)
![image](https://github.com/user-attachments/assets/624d8f59-5fc9-4325-a9f7-c931cd0d9d21)


Okay this seriously got away from me

**Comment by oOBoomberOo** [comment]
> ![image](https://github.com/user-attachments/assets/329d1362-36f1-4193-9c7f-8c697e4cbaea)

Huh, can you really use this syntax? I didn't know that, will have to add another parsing rule.

**Comment by oOBoomberOo** [comment]
The parser got a lot more complex but I think everything is covered now
![image](https://github.com/user-attachments/assets/8aa5c019-715a-4d8c-be33-bf64dc3f0814)

**Comment by Scamper10** [comment]
Wow, looks great!

Thanks for taking the time to support my weird and wonderful syntax
